export const tweets = [
    {
        id: 1,
        username: 'Showstopper_RG',
        name: 'Rohan Gupta',
        profile_pic: 'https://pbs.twimg.com/profile_images/1263531193770754048/QTaz5CRM_400x400.jpg',
        post_time: 'Dec 4',
        content: `It's all about the path you take to reverse 'One Day' to 'Day One'.`,
        content_img: null,
        likes: '1.2k',
        comments: '258',
        retweets: '122',
        is_verified: false
    },
    {
        id: 2,
        username: 'Twitter',
        name: 'Twitter',
        profile_pic: 'https://pbs.twimg.com/profile_images/1308010958862905345/-SGZioPb_400x400.jpg',
        post_time: 'Sep 22',
        content: `The only thing we want going viral is this Tweet #WearAMask`,
        content_img: 'https://pbs.twimg.com/media/EidSPNYXsAsx70i?format=jpg&name=large',
        likes: '163.7k',
        comments: '7.5k',
        retweets: '39.7k',
        is_verified: true
    },
    {
        id: 3,
        username: 'Twitter',
        name: 'Twitter',
        profile_pic: 'https://pbs.twimg.com/profile_images/1308010958862905345/-SGZioPb_400x400.jpg',
        post_time: 'Dec 3',
        content: `2020 in one word`,
        content_img: null,
        likes: '242.2k',
        comments: '110.3k',
        retweets: '108.2k',
        is_verified: true
    },
    {
        id: 4,
        username: 'MKBHD',
        name: 'Marques Brownlee',
        profile_pic: 'https://pbs.twimg.com/profile_images/1212149592403382281/cI0-xyss_400x400.jpg',
        post_time: 'Nov 24',
        content: `Oh my god I love getting good ideas when I can actually write them down`,
        content_img: null,
        likes: '26.2k',
        comments: '214',
        retweets: '506',
        is_verified: true
    },
    {
        id: 5,
        username: 'Trendulkar',
        name: 'Trendulkar',
        profile_pic: 'https://pbs.twimg.com/profile_images/1316435144618635264/VfVNhAD6_400x400.jpg',
        post_time: 'Dec 3',
        content: `On the bright side, nobody is going to ask you 'Bhai, New Year's ka plan hai?' this year.`,
        content_img: null,
        likes: '1.1k',
        comments: '9',
        retweets: '56',
        is_verified: true
    },
    {
        id: 6,
        username: 'JeffBezos',
        name: 'Jeff Bezos',
        profile_pic: 'https://pbs.twimg.com/profile_images/669103856106668033/UF3cgUk4_400x400.jpg',
        post_time: 'Feb 28',
        content: `Discussing climate, sustainability, and preserving the natural world with President @EmmanuelMacron today in Paris. #BezosEarthFund #ClimatePledge`,
        content_img: 'https://pbs.twimg.com/media/ER4QQJ6U8AAqJD3?format=jpg&name=large',
        likes: '17.8k',
        comments: '874',
        retweets: '1.4k',
        is_verified: true
    },
    {
        id: 7,
        username: 'Trendulkar',
        name: 'Trendulkar',
        profile_pic: 'https://pbs.twimg.com/profile_images/1316435144618635264/VfVNhAD6_400x400.jpg',
        post_time: 'Dec 3',
        content: `I used to spend around 10K per month on daily cab rides before COVID. Turns out I now have unexpected savings of additional 100K in the last 10 months of WFH among other things...`,
        content_img: null,
        likes: '2.4k',
        comments: '32',
        retweets: '21',
        is_verified: true
    },
    {
        id: 8,
        username: 'bewabisabix',
        name: 'x',
        profile_pic: 'https://pbs.twimg.com/profile_images/1329373939672391682/14Q0dxw7_400x400.jpg',
        post_time: 'Dec 2',
        content: `girls posing for farewell pictures`,
        content_img: 'https://pbs.twimg.com/media/EoPzH2lVcAE3008?format=jpg&name=900x900',
        likes: '5.3k',
        comments: '29',
        retweets: '417',
        is_verified: false
    }
];