export const tweets = [
    {
        id: 1,
        username: 'Showstopper_RG',
        name: 'Rohan Gupta',
        profile_pic: 'https://pbs.twimg.com/profile_images/1263531193770754048/QTaz5CRM_400x400.jpg',
        post_time: 'Dec 4',
        content: `It's all about the path you take to reverse 'One Day' to 'Day One'.`,
        content_img: null,
        likes: '1.2k',
        comments: '258',
        retweets: '122',
        is_verified: false
    },
    {
        id: 2,
        username: 'Twitter',
        name: 'Twitter',
        profile_pic: 'https://pbs.twimg.com/profile_images/1308010958862905345/-SGZioPb_400x400.jpg',
        post_time: 'Sep 22',
        content: `The only thing we want going viral is this Tweet #WearAMask`,
        content_img: 'https://pbs.twimg.com/media/EidSPNYXsAsx70i?format=jpg&name=large',
        likes: '163.7k',
        comments: '7.5k',
        retweets: '39.7k',
        is_verified: true
    },
    {
        id: 1,
        username: 'Showstopper_RG',
        name: 'Rohan Gupta',
        profile_pic: 'https://pbs.twimg.com/profile_images/1263531193770754048/QTaz5CRM_400x400.jpg',
        post_time: 'Dec 4',
        content: `It's all about the path you take to reverse 'One Day' to 'Day One'.`,
        content_img: null,
        likes: '1.2k',
        comments: '258',
        retweets: '122',
        is_verified: false
    },
    {
        id: 1,
        username: 'Showstopper_RG',
        name: 'Rohan Gupta',
        profile_pic: 'https://pbs.twimg.com/profile_images/1263531193770754048/QTaz5CRM_400x400.jpg',
        post_time: 'Dec 4',
        content: `It's all about the path you take to reverse 'One Day' to 'Day One'.`,
        content_img: null,
        likes: '1.2k',
        comments: '258',
        retweets: '122',
        is_verified: false
    },
    {
        id: 1,
        username: 'Showstopper_RG',
        name: 'Rohan Gupta',
        profile_pic: 'https://pbs.twimg.com/profile_images/1263531193770754048/QTaz5CRM_400x400.jpg',
        post_time: 'Dec 4',
        content: `It's all about the path you take to reverse 'One Day' to 'Day One'.`,
        content_img: null,
        likes: '1.2k',
        comments: '258',
        retweets: '122',
        is_verified: false
    },
    {
        id: 1,
        username: 'Showstopper_RG',
        name: 'Rohan Gupta',
        profile_pic: 'https://pbs.twimg.com/profile_images/1263531193770754048/QTaz5CRM_400x400.jpg',
        post_time: 'Dec 4',
        content: `It's all about the path you take to reverse 'One Day' to 'Day One'.`,
        content_img: null,
        likes: '1.2k',
        comments: '258',
        retweets: '122',
        is_verified: false
    },
    {
        id: 1,
        username: 'Showstopper_RG',
        name: 'Rohan Gupta',
        profile_pic: 'https://pbs.twimg.com/profile_images/1263531193770754048/QTaz5CRM_400x400.jpg',
        post_time: 'Dec 4',
        content: `It's all about the path you take to reverse 'One Day' to 'Day One'.`,
        content_img: null,
        likes: '1.2k',
        comments: '258',
        retweets: '122',
        is_verified: false
    },
    {
        id: 1,
        username: 'Showstopper_RG',
        name: 'Rohan Gupta',
        profile_pic: 'https://pbs.twimg.com/profile_images/1263531193770754048/QTaz5CRM_400x400.jpg',
        post_time: 'Dec 4',
        content: `It's all about the path you take to reverse 'One Day' to 'Day One'.`,
        content_img: null,
        likes: '1.2k',
        comments: '258',
        retweets: '122',
        is_verified: false
    }
];